'use strict'
const loremText = [
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Lacus viverra vitae congue eu consequat ac. Ut consequat semper viverra nam libero justo laoreet sit amet. Dictumst vestibulum rhoncus est pellentesque. Ut faucibus pulvinar elementum integer. Sit amet luctus venenatis lectus magna fringilla urna. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus.',
'Tortor condimentum lacinia quis vel eros. Urna id volutpat lacus laoreet non curabitur. Iaculis nunc sed augue lacus viverra. Quisque egestas diam in arcu cursus euismod. Et malesuada fames ac turpis. Blandit turpis cursus in hac habitasse platea dictumst quisque. Et ligula ullamcorper malesuada proin libero. Proin nibh nisl condimentum id venenatis a condimentum. Convallis posuere morbi leo urna molestie. Semper auctor neque vitae tempus quam. Amet cursus sit amet dictum sit amet justo donec. Sed vulputate odio ut enim blandit volutpat.',
'Justo eget magna fermentum iaculis eu. Mauris rhoncus aenean vel elit scelerisque mauris. Tempor nec feugiat nisl pretium fusce id. Nulla malesuada pellentesque elit eget gravida. Ipsum dolor sit amet consectetur adipiscing elit duis. Mauris augue neque gravida in fermentum. At imperdiet dui accumsan sit. Elit at imperdiet dui accumsan sit. Pharetra sit amet aliquam id diam. Morbi tempus iaculis urna id volutpat lacus laoreet non. Risus pretium quam vulputate dignissim suspendisse in est ante. Est ante in nibh mauris. ',
'Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Tristique magna sit amet purus gravida. Montes nascetur ridiculus mus mauris. Tincidunt eget nullam non nisi est sit amet facilisis magna. Consectetur a erat nam at lectus urna duis. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Pulvinar sapien et ligula ullamcorper malesuada proin. Tellus mauris a diam maecenas sed enim ut sem viverra. Nisi scelerisque eu ultrices vitae auctor eu. Turpis massa sed elementum tempus egestas sed.',
'Mi tempus imperdiet nulla malesuada. Elit eget gravida cum sociis natoque penatibus et magnis dis. Tincidunt augue interdum velit euismod in pellentesque massa. Pharetra sit amet aliquam id diam. Tempus urna et pharetra pharetra. Arcu dui vivamus arcu felis. Id faucibus nisl tincidunt eget nullam non nisi est. Ornare quam viverra orci sagittis eu volutpat odio. Nibh sed pulvinar proin gravida hendrerit. Rhoncus mattis rhoncus urna neque viverra. Ut ornare lectus sit amet est placerat in egestas.',
'Diam vulputate ut pharetra sit amet aliquam. Cras fermentum odio eu feugiat pretium nibh ipsum consequat. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Donec massa sapien faucibus et molestie ac. Netus et malesuada fames ac. Blandit libero volutpat sed cras ornare. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Eu volutpat odio facilisis mauris sit amet massa vitae. Neque viverra justo nec ultrices dui sapien eget mi. Nunc mattis enim ut tellus elementum.',
'Fermentum posuere urna nec tincidunt praesent. Orci nulla pellentesque dignissim enim sit. Lectus sit amet est placerat in. Pharetra massa massa ultricies mi. Neque volutpat ac tincidunt vitae. Elit sed vulputate mi sit amet mauris commodo quis imperdiet. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Fringilla ut morbi tincidunt augue interdum velit euismod in. Nisl pretium fusce id velit ut tortor. Dictum at tempor commodo ullamcorper a lacus.',
'Neque sodales ut etiam sit amet nisl purus in mollis. Ornare aenean euismod elementum nisi quis eleifend. Convallis convallis tellus id interdum velit laoreet id donec. Id aliquet lectus proin nibh nisl condimentum id venenatis. Id aliquet risus feugiat in ante metus dictum at tempor. Pretium lectus quam id leo in vitae. Quam id leo in vitae turpis. Amet nulla facilisi morbi tempus. Sollicitudin ac orci phasellus egestas tellus. Viverra orci sagittis eu volutpat odio. Nam aliquam sem et tortor consequat id.',
'In vitae turpis massa sed. Posuere urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Justo eget magna fermentum iaculis eu non diam phasellus. Proin libero nunc consequat interdum varius. Nam at lectus urna duis convallis. Tellus id interdum velit laoreet id donec ultrices. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Eu volutpat odio facilisis mauris sit amet massa vitae. Bibendum enim facilisis gravida neque convallis a cras semper auctor.',
'Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Fusce id velit ut tortor pretium. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Aliquet risus feugiat in ante metus dictum at tempor. Leo a diam sollicitudin tempor id eu nisl nunc mi. Sed libero enim sed faucibus turpis. Sit amet consectetur adipiscing elit duis.',
'Proin sed libero enim sed faucibus. Neque egestas congue quisque egestas diam in arcu cursus euismod. Senectus et netus et malesuada fames ac turpis egestas. Vestibulum lorem sed risus ultricies. Fermentum et sollicitudin ac orci. Pellentesque habitant morbi tristique senectus et netus et. Eu feugiat pretium nibh ipsum consequat nisl vel. Convallis posuere morbi leo urna molestie. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Diam ut venenatis tellus in metus.',
'Porta non pulvinar neque laoreet suspendisse. At urna condimentum mattis pellentesque id nibh tortor id. Orci a scelerisque purus semper eget duis at tellus. Et netus et malesuada fames ac turpis egestas maecenas pharetra. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Massa massa ultricies mi quis hendrerit dolor magna. At consectetur lorem donec massa sapien faucibus. Vel quam elementum pulvinar etiam non quam lacus. A diam maecenas sed enim ut sem. Lacus sed viverra tellus in hac.',
'Phasellus vestibulum lorem sed risus ultricies tristique. Lobortis elementum nibh tellus molestie nunc. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Justo donec enim diam vulputate ut. Pulvinar pellentesque habitant morbi tristique senectus et netus. Ut sem nulla pharetra diam sit amet nisl suscipit. Nunc vel risus commodo viverra maecenas. Urna cursus eget nunc scelerisque. Ut consequat semper viverra nam libero. Felis bibendum ut tristique et egestas.',
'A cras semper auctor neque vitae. Fermentum dui faucibus in ornare quam. Felis donec et odio pellentesque. Erat imperdiet sed euismod nisi. Tincidunt praesent semper feugiat nibh sed pulvinar. Quis viverra nibh cras pulvinar mattis nunc sed blandit. Nunc congue nisi vitae suscipit. Euismod lacinia at quis risus sed vulputate odio. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. At volutpat diam ut venenatis tellus in metus. Aliquam sem et tortor consequat id porta nibh venenatis.',
'Tortor dignissim convallis aenean et. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Vulputate odio ut enim blandit volutpat maecenas volutpat. Neque viverra justo nec ultrices dui sapien eget. Ac feugiat sed lectus vestibulum mattis ullamcorper velit. Tristique senectus et netus et malesuada. Euismod in pellentesque massa placerat duis ultricies lacus sed. Integer eget aliquet nibh praesent tristique magna sit amet. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida.',
'Ut aliquam purus sit amet. Euismod quis viverra nibh cras. Laoreet id donec ultrices tincidunt arcu non. Ut morbi tincidunt augue interdum. Id neque aliquam vestibulum morbi blandit cursus. Phasellus vestibulum lorem sed risus ultricies tristique. Mi tempus imperdiet nulla malesuada pellentesque. Lacinia quis vel eros donec ac odio tempor. Proin sagittis nisl rhoncus mattis. Felis donec et odio pellentesque diam volutpat commodo sed. Id diam maecenas ultricies mi.',
'Sit amet facilisis magna etiam tempor orci eu lobortis. Commodo ullamcorper a lacus vestibulum. Dis parturient montes nascetur ridiculus mus mauris vitae. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Libero enim sed faucibus turpis in eu mi bibendum neque. Eget egestas purus viverra accumsan in nisl nisi scelerisque. Adipiscing at in tellus integer feugiat scelerisque. Facilisis gravida neque convallis a cras semper. Enim blandit volutpat maecenas volutpat blandit aliquam.',
'Ut placerat orci nulla pellentesque dignissim enim. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Id leo in vitae turpis massa sed. Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna. Neque viverra justo nec ultrices dui sapien eget mi. Lacus luctus accumsan tortor posuere ac ut. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Fringilla ut morbi tincidunt augue interdum velit euismod in. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi.',
'iverra vitae congue eu consequat ac. Dui accumsan sit amet nulla. Amet est placerat in egestas erat imperdiet. Ullamcorper velit sed ullamcorper morbi tincidunt. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Mauris pharetra et ultrices neque ornare aenean euismod elementum. Aliquam vestibulum morbi blandit cursus. At urna condimentum mattis pellentesque id. Amet tellus cras adipiscing enim eu turpis egestas pretium. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae. Lacus luctus accumsan tortor posuere.',
'Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Blandit turpis cursus in hac habitasse platea dictumst quisque. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Scelerisque fermentum dui faucibus in ornare quam viverra orci. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis.',
'Sagittis id consectetur purus ut. Tincidunt eget nullam non nisi est sit amet facilisis magna. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Eu augue ut lectus arcu bibendum at varius vel pharetra. Laoreet sit amet cursus sit amet dictum sit amet. Duis ut diam quam nulla porttitor massa id. Enim diam vulputate ut pharetra sit amet aliquam id diam. Semper viverra nam libero justo laoreet. Venenatis cras sed felis eget velit aliquet sagittis id consectetur. Nibh tortor id aliquet lectus proin nibh nisl condimentum.',
'aecenas volutpat blandit aliquam etiam erat velit. Mauris a diam maecenas sed enim ut. Sed euismod nisi porta lorem mollis aliquam. Amet nisl purus in mollis nunc sed id semper. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Consectetur lorem donec massa sapien faucibus et molestie ac. Neque viverra justo nec ultrices dui sapien eget. Orci ac auctor augue mauris augue neque gravida in fermentum. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Egestas pretium aenean pharetra magna ac placerat vestibulum.',
'Convallis a cras semper auctor neque vitae. At consectetur lorem donec massa. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Cursus turpis massa tincidunt dui ut ornare lectus. Sed euismod nisi porta lorem mollis. Ornare arcu dui vivamus arcu felis bibendum ut tristique et. Viverra orci sagittis eu volutpat odio facilisis. Blandit turpis cursus in hac habitasse platea dictumst quisque.',
'Platea dictumst quisque sagittis purus sit amet volutpat consequat. Eu nisl nunc mi ipsum faucibus vitae. Integer enim neque volutpat ac tincidunt vitae semper quis lectus. Mi sit amet mauris commodo quis imperdiet. Morbi quis commodo odio aenean sed. Nibh praesent tristique magna sit amet purus gravida quis. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Ipsum suspendisse ultrices gravida dictum. Lacus vestibulum sed arcu non odio euismod. Nisi vitae suscipit tellus mauris a diam maecenas sed enim.',
'Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Quisque non tellus orci ac auctor. Feugiat vivamus at augue eget arcu. In nisl nisi scelerisque eu ultrices vitae auctor. Facilisi cras fermentum odio eu feugiat pretium. Magna fringilla urna porttitor rhoncus dolor purus non. Habitasse platea dictumst quisque sagittis. In iaculis nunc sed augue lacus. Lacinia at quis risus sed vulputate odio ut enim. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae.',
'Vitae auctor eu augue ut lectus arcu bibendum at. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Convallis tellus id interdum velit laoreet. Amet justo donec enim diam. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Tellus mauris a diam maecenas sed enim. Fermentum iaculis eu non diam. Netus et malesuada fames ac. Eu volutpat odio facilisis mauris. Morbi tempus iaculis urna id volutpat lacus laoreet. Elit duis tristique sollicitudin nibh sit amet.',
'Pellentesque habitant morbi tristique senectus et netus et. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Duis ultricies lacus sed turpis tincidunt. Pellentesque eu tincidunt tortor aliquam nulla. Scelerisque purus semper eget duis. Amet venenatis urna cursus eget nunc scelerisque. Iaculis nunc sed augue lacus. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Libero enim sed faucibus turpis in. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor.',
'Magna sit amet purus gravida quis blandit turpis cursus. Nisl nisi scelerisque eu ultrices. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Enim tortor at auctor urna nunc id cursus metus. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Consectetur adipiscing elit ut aliquam purus sit amet. Mattis pellentesque id nibh tortor id aliquet lectus proin. Consequat semper viverra nam libero justo. Lacus luctus accumsan tortor posuere. In aliquam sem fringilla ut.',
'Ut pharetra sit amet aliquam id diam maecenas ultricies mi. Purus non enim praesent elementum. Nullam vehicula ipsum a arcu. Morbi quis commodo odio aenean sed adipiscing diam. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. At consectetur lorem donec massa sapien faucibus et molestie. Commodo ullamcorper a lacus vestibulum sed arcu. Dictum sit amet justo donec enim diam. Nec ullamcorper sit amet risus nullam eget felis eget. Imperdiet dui accumsan sit amet nulla facilisi morbi. Ornare arcu dui vivamus arcu felis bibendum ut tristique.',
'Interdum velit euismod in pellentesque massa placerat duis ultricies lacus. Neque gravida in fermentum et sollicitudin ac orci phasellus. Arcu bibendum at varius vel pharetra vel turpis nunc. Volutpat diam ut venenatis tellus in metus. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Id consectetur purus ut faucibus pulvinar elementum integer. Arcu odio ut sem nulla pharetra diam sit amet. Vitae aliquet nec ullamcorper sit amet risus. Vel facilisis volutpat est velit egestas. Nibh tortor id aliquet lectus proin.'
];

const numOfParagraphs = document.querySelector('#numofparagraphs');
const button = document.querySelector('.button');
const loremOutput = document.querySelector('.output-lorem');

button.addEventListener('click', function(e) {
    e.preventDefault();
    const paragraphs = parseInt(numOfParagraphs.value);
    let output = loremText.slice(0, paragraphs);
    output = output.map(item => `<p>${item}</p>`).join('');
    loremOutput.innerHTML = output;
})